### ISSUE TITLE
Highlight conflicts with normal highlight

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-narrow#14]
This is a line highlighted by narrow:

![screenshot 2016-11-08 14 05 12](https://cloud.githubusercontent.com/assets/1909539/20119188/683159e0-a5bc-11e6-811f-7bf8c34ec858.png)

Notice that currently, I have a region selected. You can't see it because narrow's highlight is of the same color.

**Comment by t9md** [comment]
Are you using atom-beta or stable?

From new beta we can use keyframe css animation which is I introduced in latest vmp and cursor-history feature.

I'm thinking use flashing by keyframe since even if I tweak color, overwrapping selection is difficult to distinguish without completely remove narrow's highlight, so flash and disappear is better I think.

**Comment by chenglou** [comment]
Atom stable. Alternatively, narrow can highlight using a different color right? Or just border highlight, like [highlight-selected](https://atom.io/packages/highlight-selected)

**Comment by t9md** [comment]
![underline-hl](https://cloud.githubusercontent.com/assets/155205/20398016/07357e44-ad2f-11e6-958c-faa01f82471e.gif)



will evaluate ux of underline hl for a while
