### ISSUE TITLE
Ripgrep escaping `\` leads to no results

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#171]
Hi,
found an issue with recently implemented `ripgrep` support (thanks for that!).

When searching for string `a/b/c` and search set to `rg` no results are yielded (`ag` does ok).

When run directly 
`rg 'a\/b\/c'`
yields 
`Error parsing regex near 'a\/b\/c' at character offset 2: Unrecognized escape sequence: '\/'.`

Moreover, replacing `\/` with `/` yields correct results in CLI for both `rg` and `ag`.

Seems like that's because "rust's regex engine doesn't let you willy nilly escape any character".
https://github.com/BurntSushi/ripgrep/issues/102#issuecomment-249620557

Here are some thoughts:

1. Maybe escaping `/` for `\/` is not useful and can be dropped? Was it a work around something?
2. If rg/ag exits with non 0 code then the output should be output within `narrow`?

**Comment by t9md** [comment]
Thanks for investigating issue very clearly.

> Maybe escaping / for \/ is not useful and can be dropped? Was it a work around something?

I changed to use `--fixed-strings` option for both `ag` and `rg`.
I avoided this approach originally since I have to manage TWO pattern for UI syntax highlight and search pattern.

But I changed my mind to accept, since I don't want to skipping escape one-by-one each time issue appears.

> If rg/ag exits with non 0 code then the output should be output within narrow?

I changed to write stderr to `console.warn`, outputting on narrow-editor is difficult since it's always assuming correct item is passed.(item must be object with point and text field)
