### ISSUE TITLE
Feature request: update search results for opened file immediately

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#181]
Use case:

Perform search for string `abc`. String is found 4 times in 2 files (2 entries per file). Open first file. Delete/alter both strings `abc`.

Do not save file.

When navigating with shortcuts I press `go to next entry` after deleting both `abc`s and this is a no-op because there is no such second entry already and next/previous navigation is broken.

Possible solutions:
- checkbox "autosave when navigating with narrow if buffer was changed"
- exclude current file being edited from search results, save current buffer to tmp file and run search on it and replace search results

What do you think?

**Comment by t9md** [comment]
> checkbox "autosave when navigating with narrow if buffer was changed"

I don't want to do this, but this can be done by user's init.coffee script

- auto save file on-did-change timing when narrow-search editor was opened in workspace.

But I want you just hit `cmd-s`. in the first place.

> exclude current file being edited from search results, save current buffer to tmp file and run search on it and replace search results

Yes, understandable. But again I want to avoid this kind of dirty if possible.

If I would go to this direction.
 - render initial result with `ag` or `rg`, since it's fast.
 - on file change, invalidate entry in modified file and update entry by collecting item by Atom's `editor.scan`.
  - This allow scan editor's text which is not yet write out to disk.
 - But how to do when search option changed?
  - We have to re-scan whole entry from disk, but when there is modified state file, need to exclude that items and replace it with the result of `editor.scan`
  - So I have to manage modified files, and respect it when search option(whole-word, ignore-case) changed.
  - This definitely introduce complexity to code base, does it worth to do? How many situation user hit this?

Just hit `cmd-s` to save is first solution.

**Comment by t9md** [comment]
After thinking , I like **current* explicitly save and refresh behavior.
I use narrow-editor item list as kind of TODO list which item is removed when I save buffer.
Let's say removing unused functions scattered across files.
I want removed functions item on narrow-editor is removed on explicit save.

I know there is different opinion, usecase, preference, I'm explaining why I'm not motivated to implement this feature.
Of cource another reason is it need extra dirty work to support this feature.
If it's easy and amount of code I have to add is small, my motivation would be different.

**Comment by t9md** [comment]
Wow, I will evaluate  this next! I'm not motivated to fix this 👍 👍 👍
