### ISSUE TITLE
Feature Request: Possible for search provider to immediately open Narrow?

### ISSUE THREAD

**Issue by dan-weaver** [t9md/atom-narrow#184]
Hi! First of all, cool project very glad something like this is coming along (vim plus is great too!).  I was wondering if it was by design or preference that when opening narrow via the project-search provider you had to initially specify a search term in the text input BEFORE the new narrow buffer opens.  In addition to this it seems like subsequent changes to the search term in narrow are scoped by the initial query from the text box.

Alternative idea: Could the narrow pane open immediately when you use project-search and incrementally return results.. (I think this is more in line with how Helm (emacs) works.

It's possible this is already the intended behavior and something with my configuration is incorrect.  I have ag installed.

Atom version: 1.16.0
Narrow version: 0.39.1

**Comment by dan-weaver** [comment]
Looking through the code some more, it looks like this was a conscious design..  I think I misunderstood what providers were. I thought that they implemented a search function, but it looks like they actually provide a real set of results which are then further searchable from the narrow ui.  Is this correct?  Therefore, there's probably no easy way to implement what I had in mind at the moment.

What would your prescribed workflow be in the event that I wanted to search a new term from narrow after having already entered the narrow ui? I suppose re initializing Narrow: search is the easiest option?  Not too bad really!  I'll close this one out, but was wondering if you could validate my above understanding of providers.

**Comment by t9md** [comment]
I once have this idea you mentioned( search take search-term from narrow-editor so that re-edit search-term ).

https://github.com/t9md/atom-narrow/issues/51

But I postponed it.
I basically already comfortable with current behavior.
And yes, your understanding is correct.
The provider is just provide items, then narrow-ui( or narrow-editor ) narrows the item by query.
Also have some info on https://github.com/t9md/atom-narrow/wiki/Spec

But there is one exceptional provider `narrow-scan`, with this provider, first query you input to narrow-editor generate new items.
So your suggestion is to bring this narrow-scan's behavior to `narrow-search`.

But problem is performance, and my motivation to re-write.

For re-start search, I map from `enter`, so searching is  just hit `enter` in `normal-mode`.
Not tedious for me.

```coffeescript
'atom-text-editor.vim-mode-plus.normal-mode':
  'enter': 'narrow:search-by-current-word'
```

If I need manual term search with explicit search-term imput from bare `narrow:search`.
You can use `ctrl-p`, `ctrl-n` to re-insert search-term from history.
This is a bit tedious.

But in 90% of case I use `search-by-current-word` vie `enter`.

**Comment by dan-weaver** [comment]
cool! Yes I think current behavior is pretty good..  Closing issue. Thanks for your response!
