### ISSUE TITLE
Feature request: narrow:select file

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-narrow#198]
Hello @t9md, just found *narrow* and it's awesome as all your projects. Thanks

It would be awesome if narrow can be used as file selector, like Ctrl-p and unite. What do you think?

**Comment by t9md** [comment]
Narrow already have `narrow:select-file` but this for different purpose.
Used for filter items on `narrow-editor` by filePath basis.

- You can start `narrow:select-file` by `s` key if you are vim-mode-plus user
- Or click folder icon on control-bar of narrow-ui

For your request, I don't want enhance narrow as open everything package.
I'm intentionally limiting the area narrow cover.
I defined narrow as code-navigation tool.
This is design decision. 

Why not use Atom's fuzzy-finder?

**Comment by slavaGanzin** [comment]
I'm using fuzzy-finder, and advanced-open-file, and now narrow. And all of them has different interface, it means I need to do different actions to achieve same result: open file I'm thinking about. Less interfaces - less thinking.

I saw select-file mode and I thought it would be great to reuse it for opening files by name.

I appreciate your design decision.

**Comment by t9md** [comment]
Thanks for understanding.
I understand your motivation, and agree that unified interface to interact is better than many different interfaces.

But I intentionally make narrow purpose-limiting to make primal function(= code navigation) further better.

This issue is memo at very early stage of narrow. 
But I changed my mind. 

https://github.com/t9md/atom-narrow/issues/21
