### ISSUE TITLE
helm-swoop style search

### ISSUE THREAD

**Issue by crucialfelix** [t9md/atom-narrow#2]
Hi - just trying out your alpha version.  This is something I would love to have, thanks for your work !

This is what you are trying to do, right ? https://github.com/ShingoFukuyama/helm-swoop
That would be awesome.

`Narrow: Search` and then j/k ... then `Narrow UI: Reveal Item` kind of works to get something like helm-swoop. 

I tried it with auto-reveal. It would be nice if it selects the line too. 

I don't want to file a specific bug because I'm sure you know what to work on next. 

Just offering encouragement !

Looking forward to updates !

**Comment by t9md** [comment]
Thanks for encouraging comment. I love it!
And will definitely check swoop you mentioned.
One of complex challenge is ... I'm vim-mode-plus user(yes I'm maintaining by myself) and don't care non-vim-mode-plus user, but narrow is not assuming vim-mode(or vim-mode-plus).
If I can focus target user to vim-mode-plus, I can improve operation efficiency.

helm if for emacs
unite is for vim
but narrow have to support Atom which have emacs-mode, vim-mode etc. really necessary?(question to my self)...

**Comment by crucialfelix** [comment]
the thing about swoop is that it was SO fast to search, go through the results and then close the swoop window. you can easily do this, you are nearly there.

there is a video too: https://www.youtube.com/watch?v=S-R98NMr9s0 
at 1:00 you can see him actually using it (not just configuring it)

**Comment by t9md** [comment]
Are you vim or emacs user?
The other issue uou reported indicates vim-mode user, but curious.
And if you use vim-mode, then try vim-mode-plus too.

**Comment by t9md** [comment]
v0.2.0 released. GIF on readme updated. 
- Special integration with vim-mode-plus.
- Close narrow-ui on confirm. 
- Use custom gutter to indicate current selected-item(still have corner case bug).
- `narrow:lines`, `narrow:fold` have autoPreview enabled.
- [breaking] Renamed commands from `reveal` to `preview`.

**Comment by crucialfelix** [comment]
I was using spacemacs, so both vim and emacs. Best of both worlds, but still things fall apart very easily if you mess with them.

I will definitely give vim-mode-plus a try. I've noticed you working on it quite a bit for a while. 

I just tried the update 3 and its working great ! 
I will assign key commands to it and live with it for a while. 
thank you !

**Comment by t9md** [comment]
Thanks for answering understood, space-emacs looks good especially it's space leading keybinding design.

And line and search both now support fuzzy input search(disabled by default).
For latest narrow, it works far better with vim-mode-plus, since I added built-in integration with vim-mode-plus.
So when you enter insert-mode with `i` cursor move to top line so that you can quickly continue to add narrowing word.
And you can directly start narrow:line, narrow:search, narrow:search-current-project from **vim-mode-plus's search** input.

So workflow like this, I start searching by vim-mode-plus's incremental search and then `ctrl-cmd-o` immediately start `narrow:search` with currently searching keyword.
