### ISSUE TITLE
Additional filtering should cut original search word

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-narrow#264]
Hello. I'll show this on example:

```python

def prepareDefinition():
  return

def prepare(): 
  return
```

Open narrow and search for 'def':

```
def prepareDefinition():
def prepare():
```

Then add additional filtering(we want go to prepareDefinition). "def def" result is same as previous:
```
def prepareDefinition():
def prepare():
```

Pretty minor, but annoying.

I can fix it, but maybe this was intentional?

Thanks

**Comment by t9md** [comment]
You expect "def def" input's 2nd def only pick `def prepareDefinition()` since it's only item which "def" appears twice right?

Which is not how I designed narrow for.
So I don't need immediate fix for now.

In `search` provider, 1st `def` is passed to `ag` or `rg`, then 2nd "def" is used to filter result item.

If you want pick `prepareDefinition`, you can pick it by query `def Def`(you need smartCase or caseSensitive enable for query).

I'm not sure your approach to **fix** this.
But I want filter query order agnostic, means "def foo bar" show exactly same items as "def bar foo".

**Comment by slavaGanzin** [comment]
What i was thinking of:
While filtering cut (highlighted by ```ag/rg```) "def" from results. But as I understand now it doesn't worth it, because searcher will highlight two highlighted "def"
```

*def* prepareDefinition():
def prepare*Def*inition():

```

which are internally merge by narrow.


Thanks for you answer. And for narrow in common.
